### ISSUE TITLE
Option for setting a tag on publish

### ISSUE THREAD

**Issue by Jonzy3000** [timotto/concourse-npm-resource#18]
Hello, would it be possible to have a param for setting a tag when publishing that's equivalent to the --tag flag? Something like

```
    params:
      version: version/version
      path: dist
      tag: 'dev'
```
